title: 张召的博客
description: 怕什么真理无穷, 进一寸有进一寸的欢喜
show_downloads: true

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://kougazhang.github.io" # change this to the base hostname & protocol for your site


google_analytics: G-G8NG8E6SGC

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%Y-%m-%d %H:%M"

theme: jekyll-theme-cayman # leave it empty

# 插件
plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-seo-tag

# 在新标签页中打开链接
target-blank:
  rel: nofollow

# 导航栏
header_page_refs: ['now', 'logBook', 'skillTree', 'contact', 'about']
