title: 张召的博客
description: 不愿随波而逝, 故提笔以记之
show_downloads: true

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://kougazhang.github.io" # change this to the base hostname & protocol for your site


google_analytics: G-G8NG8E6SGC

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman # leave it empty

plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-seo-tag

target-blank:
  rel: nofollow

header_page_refs: ['now', 'about', 'contact']
